select	correoelectronico,
		nombre,
		nombresucursal,
		apellidopaterno,
		apellidomaterno,
		genero,
		estado,
		ciudad,
		colonia,
		calle,
		numero,
		codigopostal,
		telefono,
		rfc,
		nss,
		null as nolicencia,
		null as tienebici, 
		null as tienemoto,	
		0 as numerocedulaprofesional,
		0 as consultasanio,
		0 as consultasmes,
		0 as consultasdia
		from public.general
union 

((select correoelectronico,
		nombre,
		nombresucursal,
		apellidopaterno,
		apellidomaterno,
		genero,
		estado,
		ciudad,
		colonia,
		calle,
		numero,
		codigopostal,
		telefono,
		rfc,
		nss,
		null as nolicencia,
		null as tienebici,
		null as tienemoto,
  		0 as numerocedulaprofesional,
		0 as consultasanio,
		0 as consultasmes,
		0 as consultasdia
		from public.intendencia	
union
select correoelectronico,
		nombre,
		nombresucursal,
		apellidopaterno,
		apellidomaterno,
		genero,
		estado,
		ciudad,
		colonia,
		calle,
		numero,
		codigopostal,
		telefono,
		rfc,
		nss,
		nolicencia,
		tienebici,
		tienemoto,
  		0 as numerocedulaprofesional,
		null as consultasanio,
		null as consultasmes,
		null as consultasdia
from public.repartidor)
 union
(select m.correoelectronico,
		c.nombresucursal,
		m.nombre,
		m.apellidopaterno,
		m.apellidomaterno,
		m.genero,
		m.estado,
		m.ciudad,
		m.colonia,
		m.calle,
		m.numero,
		m.codigopostal,
		m.telefono,
		m.rfc,
		m.nss,
		null as nolicencia,
		null as tienebici,
		null as tienemoto,
		m.numerocedulaprofesional,
		m.consultasanio,
		m.consultasmes,
		m.consultasdia
 
from public.medico as m
left join public.contarcon as c
on m.correoelectronico = c.correoelectronicomedico))
limit 10;

